MyWebApp/Models/Learner.cs
namespace MyWebApp.Models
{
    public class Learner
    {
        public Learner()
        {
            Enrollments = new HashSet<Enrollment>();
        }
        public int LearnerID { get; set; }
        public string LastName { get; set; }
        public string FirstMidName { get; set; }
        public DateTime EnrollmentDate { get; set; }
        public int MajorID { get; set; }

        public virtual Major? Major { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }

    }
}

MyWebApp/Controllers/LearnerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyWebApp.Data;
using MyWebApp.Models;
using System.Linq;

namespace MyWebApp.Controllers
{
	public class LearnerController : Controller
	{
		private readonly SchoolContext _context;

		public LearnerController(SchoolContext context)
		{
			_context = context;
		}

		public IActionResult Index()
		{
			var learners = _context.Learners.Include(m => m.Major).ToList();
			return View(learners);
		}

		public IActionResult Delete(int id)
		{
			var learner = _context.Learners
				.Include(l => l.Major)
				.Include(e => e.Enrollments)
				.FirstOrDefault(m => m.LearnerID == id);

			if (learner == null)
			{
				return NotFound();
			}

			if (learner.Enrollments.Any())
			{
				return Content("This learner has some enrollments, can't delete");
			}

			return View(learner);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult DeleteConfirmed(int id)
		{
			var learner = _context.Learners.Find(id);
			if (learner == null)
			{
				return NotFound();
			}

			_context.Learners.Remove(learner);
			_context.SaveChanges();

			return RedirectToAction(nameof(Index));
		}

		public IActionResult Edit(int id)
		{
			var learner = _context.Learners.Find(id);
			if (learner == null)
			{
				return NotFound();
			}

			ViewBag.MajorId = new SelectList(_context.Majors, "MajorID", "MajorName", learner.MajorID);
			return View(learner);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(int id, [Bind("LearnerID,FirstMidName,LastName,MajorID,EnrollmentDate")] Learner learner)
		{
			if (id != learner.LearnerID)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(learner);
					_context.SaveChanges();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!LearnerExists(learner.LearnerID))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			ViewBag.MajorID = new SelectList(_context.Majors, "MajorID", "MajorName", learner.MajorID);
			return View(learner);
		}

		public IActionResult Create()
		{
			ViewBag.MajorID = new SelectList(_context.Majors, "MajorID", "MajorName");
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create([Bind("FirstMidName,LastName,MajorID,EnrollmentDate")] Learner learner)
		{
			if (ModelState.IsValid)
			{
				_context.Learners.Add(learner);
				_context.SaveChanges();
				return RedirectToAction(nameof(Index));
			}
			ViewBag.MajorID = new SelectList(_context.Majors, "MajorID", "MajorName", learner.MajorID);
			return View(learner);
		}

		private bool LearnerExists(int id)
		{
			return _context.Learners.Any(e => e.LearnerID == id);
		}
	}
}

MyWebApp/Views/Learner/Create.cshtml
@{
	ViewData["Title"] = "Thêm";
	Layout = "~/Views/Shared/MyLayout.cshtml";
}

@model Learner
<div class="ms-2 mx-2">
	<h1>Create</h1>
	<div asp-validation-summary="All" class="text-danger"></div>
	<form asp-controller="Learner" asp-action="Create" method="post" class="mt-3">
		<div style="margin-top:7px" class="form-group row">
			<label asp-for="FirstMidName" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="FirstMidName" class="form-control" placeholder="First Mid Name">
			</div>
			<span asp-validation-for="FirstMidName" class="text-danger"></span>
		</div>
		<div style="margin-top:7px" class="form-group row">
			<label asp-for="LastName" class="col-sm-2 col-form-label"></label> <div class="col-sm-10">
				<input asp-for="LastName" class="form-control" placeholder="Last Name">
			</div>
			<span asp-validation-for="LastName" class="text-danger"></span>
		</div>

		<div style="margin-top:7px" class="form-group row">
			<label asp-for="MajorID" class="col-sm-2 col-form-label"></label>
				<div class="col-sm-10">
					<select asp-for="MajorID" class="custom-select mr-sm-2" 
							asp-items="@ViewBag.MajorID"></select>
				</div>
				<span asp-validation-for="MajorID" class="text-danger"></span>
		</div>

		<div style="margin-top:7px" class="form-group row">
			<label asp-for="EnrollmentDate" class="col-sm-2 col-form-label"></label> 
			<div class="col-sm-10">
				<input asp-for="EnrollmentDate" class="form-control">
			</div>
			<span asp-validation-for="EnrollmentDate" class="text-danger"></span>
		</div>

		<div style="margin-top:10px" class="form-group row">
			<div class="col-sm-10">
				<button type="submit" class="btn btn-primary">Create</button>
			</div>
		</div>
	</form>
</div>

MyWebApp/Views/Learner/Delete.cshtml
@{
	ViewData["Title"] = "Xóa";
Layout = "~/Views/Shared/MyLayout.cshtml";
}

@model Learner
<div class="ms-2 mx-2">
	<h1>Xóa</h1>
	<h3>Bạn có muốn xóa?</h3>
	<h4>Learner</h4>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.FirstMidName)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.FirstMidName)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.LastName)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.LastName)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Major)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Major.MajorName)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.EnrollmentDate)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.EnrollmentDate)
		</dd>
	</dl>
	<form asp-action="Delete">
		<input type="hidden" asp-for="@Model.LearnerID" />
		<input type="submit" value="Delete" class="btn btn-danger" /> | 
		<a asp-action="Index">Back to List</a>
	</form>
</div>

MyWebApp/Views/Learner/Edit.cshtml
@{
	ViewData["Title"] = "Sửa";
	Layout = "~/Views/Shared/MyLayout.cshtml";
}
@model Learner
<div class="ms-2 mx-2">
	<h1>Edit</h1>
	<div asp-validation-summary="All" class="text-danger"></div>
	<form asp-controller="Learner" asp-action="Edit" asp-route-id="@Model.LearnerID"method="post" class="mt-3">
		<input type="hidden" asp-for="LearnerID" />
		<div style="margin-top:7px" class="form-group row">
			<label asp-for="FirstMidName" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="FirstMidName" class="form-control" placeholder="First Mid Name">
			</div>
			<span asp-validation-for="FirstMidName" class="text-danger"></span>
		</div>
		<div style="margin-top:7px" class="form-group row">
			<label asp-for="LastName" class="col-sm-2 col-form-label"></label> 
			<div class="col-sm-10">
				<input asp-for="LastName" class="form-control" placeholder="Last Name">
			</div>
			<span asp-validation-for="LastName" class="text-danger"></span>
		</div>

		<div style="margin-top:7px" class="form-group row">
			<label asp-for="MajorID" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<select asp-for="MajorID" class="custom-select mr-sm-2" asp-items="@ViewBag.MajorID"></select>
			</div>
			<span asp-validation-for="MajorID" class="text-danger"></span>
		</div>

		<div style="margin-top:7px" class="form-group row">
			<label asp-for="EnrollmentDate" class="col-sm-2 col-form-label"></label> 
			<div class="col-sm-10">
				<input asp-for="EnrollmentDate" class="form-control">
			</div>
			<span asp-validation-for="EnrollmentDate" class="text-danger"></span>
		</div>

		<div style="margin-top:10px" class="form-group row">
			<div class="col-sm-10">
				<button type="submit" class="btn btn-primary">Edit</button>
			</div>
		</div>
	</form>
</div>

MyWebApp/Views/Learner/Index.cshtml
@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/MyLayout.cshtml";
}
@model IEnumerable<Learner>
<div class="ms-2 mx-2">
	<h1>Learner List</h1>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Mã</th>
				<th>Tên</th>
				<th>Họ</th> 
				<th>Ngành</th>
				<th>Ngày Nhập Học</th> 
				<th>Chức năng</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var s in Model)
			{
				<tr>
					<td>@s.LearnerID</td>
					<td>@s.FirstMidName</td>
					<td>@s.LastName</td>
					<td>@s.Major.MajorName</td> 
					<td>@s.EnrollmentDate</td>
					<td><a asp-action="Edit" asp-route-id="@s.LearnerID">Edit</a>|<a asp-action="Delete" 
						   asp-route-id="@s.LearnerID">Delete</a></td>
				</tr>
			}
		</tbody> 
		</table>
		<a asp-action="Create" class="btn btn-primary">Create New Student</a> </div>
</div>